name: 'Frontend: Publish'

on:
  push:
    branches: ['master', 'main']

jobs:
  exists:
    name: Exists
    uses: ./.github/workflows/frontend-exists.yml
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: exists
    if: needs.exists.outputs.exists == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Init Thrift
        uses: valitydev/action-setup-thrift@v1.0.0
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run codegen
      - name: Version Up
        run: npm version prerelease --preid ${GITHUB_SHA::7} --no-git-tag-version
      - name: Publish NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
