name: 'Frontend: Exists'

on:
  pull_request:
    branches: ['*']

jobs:
  frontend-exists:
    name: Exists
    runs-on: ubuntu-latest
    outputs:
      files_exists: ${{ steps.check_files.outputs.files_exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "package.json"
